"""
featurise_ISO_TRI_BI.py

Featurizes the ISO, TRI, and BI ensembles using the Best-Vendruscolo model contacts.
This script runs featurises the sliced IsoValidation ensembles Iso-BI (filtered) and Iso-TRI (initial) using the JAXENT featurisation methods.

Requirements:
    - Trajectory files (e.g., TeaA_ISO_bi.xtc, TeaA_TRI.xtc)
    - Generated by data/get_HDXer_AutoValidation_data.py

Usage:
    python jaxent/examples/1_IsoValidation_OMass/fitting/jaxENT/featurise_ISO_TRI_BI.py

Output:
    - Features (.npz) and topology (.json) in fitting/jaxENT/_featurise/
"""

import os
import time

import jax.numpy as jnp

from jaxent.examples.common.loading import load_HDXer_kints, featurise_trajectory
from jaxent.src.custom_types.config import FeaturiserSettings
from jaxent.src.models.HDX.BV.forwardmodel import BV_model_Config


def main():
    # Define trajectories and topology
    tri_modal_trajectory = "sliced_trajectories/TeaA_filtered_sliced.xtc"
    bi_modal_trajectory = "sliced_trajectories/TeaA_initial_sliced.xtc"
    topology = "TeaA_ref_closed_state.pdb"  # TeaA_ref_open_state.pdb

    hdxer_kint_path = "../../data/out__train_TeaA_auto_VAL_1Intrinsic_rates.dat"
    hdxer_kint_path = os.path.join(os.path.dirname(__file__), hdxer_kint_path)
    if not os.path.exists(hdxer_kint_path):
        raise FileNotFoundError(f"HDXer kint file could not be found: {hdxer_kint_path}")

    # Load intrinsic rates from .dat file
    hdxer_kint_data = load_HDXer_kints(hdxer_kint_path)
    hdxer_kints = hdxer_kint_data[0]  # Extract kints from the tuple
    hdxer_top = hdxer_kint_data[1]  # Extract topology from the tuple

    print(f"Loaded intrinsic rates: {hdxer_kints.shape}")
    print(f"Loaded topology length: {len(hdxer_top)}")

    # Update traj_dir to correct relative path
    traj_dir = "../../data/_Bradshaw/Reproducibility_pack_v2/data/trajectories"
    output_dir = os.path.join(os.path.dirname(__file__), "_featurise")
    traj_dir = os.path.join(os.path.dirname(__file__), traj_dir)

    if not os.path.exists(traj_dir):
        raise FileNotFoundError(f"Trajectory directory could not be found: {traj_dir}")

    # Ensure output directory exists
    if not os.path.exists(output_dir):
        os.makedirs(output_dir)

    # Configure BV model
    bv_config = BV_model_Config()
    bv_config.timepoints = jnp.array([0.167, 1.0, 10.0, 60.0, 120.0])

    # Configure featuriser
    featuriser_settings = FeaturiserSettings(name="ISO", batch_size=None)

    # Construct file paths
    top_path = os.path.join(traj_dir, topology)
    bi_path = os.path.join(traj_dir, bi_modal_trajectory)
    tri_path = os.path.join(traj_dir, tri_modal_trajectory)

    trajectories_to_process = [(tri_path, "iso_tri"), (bi_path, "iso_bi")]

    for traj_path, output_name in trajectories_to_process:
        featurise_trajectory(
            trajectory_path=traj_path,
            topology_path=top_path,
            output_dir=output_dir,
            output_name=output_name,
            bv_config=bv_config,
            featuriser_settings=featuriser_settings,
            kint_data=hdxer_kint_data,
        )


if __name__ == "__main__":
    start = time.time()
    main()
    end = time.time()
    print("Featurisation complete.")
    print(f"Elapsed time: {end - start:.2f} seconds")
