#!/usr/bin/env python3
"""
minimise_ensemble.py

In-vacuo constrained minimisation of NeuralPLexer protein–ligand complex
ensembles produced by combine_outputs.py.

Workflow per frame
------------------
  1. Parse combined complex PDB (complex_rank*.pdb).
  2. Detect Ca²⁺/Ca²⁺ clashes; for each clashing pair remove the ion with
     fewer oxygen contacts within ``--ca-o-cutoff`` Å.  Pairs are resolved
     greedily in ascending distance order.
  3. Build a hybrid OpenMM force field:
       Protein  → AMBER ff14SB  (PDBFixer adds missing atoms + Hs)
       Ca²⁺     → AMBER Ca²⁺ parameters  (bundled in amber14-all.xml)
       CDZ      → OpenFF Sage 2.1.0
  4. Harmonic positional restraints on protein Cα atoms + Ca²⁺ ions
     (default k = 1000 kJ/mol/nm²).  CDZ ligands are completely unrestrained.
  5. In-vacuo L-BFGS minimisation (NoCutoff; prefers CUDA → OpenCL → CPU).
  6. Write individual PDB files with CONECT records for CDZ bonds.
     Filename encodes final Ca²⁺ and CDZ counts:
       complex_rank{R}_plddt{P}_ca{N}_cdz{M}_minimised.pdb

Requirements
------------
    openmm openmmforcefields 'openff-toolkit>=0.14' openff-units
    pdbfixer rdkit MDAnalysis numpy

Usage
-----
    python minimise_ensemble.py \\
        --input-dir  combined_outputs/ \\
        --ligand-sdf 85H_ideal.sdf    \\
        [--output-dir minimised/]     \\
        [--ca-clash-threshold 3.5]    \\
        [--ca-o-cutoff 3.0]           \\
        [--restraint-k 1000.0]        \\
        [--max-iterations 2000]       \\
        [--top-n 5]

Notes
-----
* The heavy-atom ordering in the combined PDB is assumed to match the
  85H_ideal.sdf template (guaranteed when combine_outputs.py is used
  without post-processing).
* H atoms for CDZ are generated by RDKit from the heavy-atom geometry.
* H atoms for the protein are added by PDBFixer at pH 7.0.
"""

from __future__ import annotations

import argparse
import io
import os
import re
import sys
import tempfile
import traceback
import warnings
from pathlib import Path

import MDAnalysis as mda
import numpy as np
import openmm as mm
import openmm.app as app
import openmm.unit as unit
from openff.toolkit import Molecule as OFFMolecule
from openff.toolkit import Topology as OFFTopology
from openff.units import unit as off_unit
from openmmforcefields.generators import SystemGenerator
from pdbfixer import PDBFixer
from rdkit import Chem
from rdkit.Chem import AllChem

warnings.filterwarnings("ignore")


# ─────────────────────────────────────────────────────────────────────────────
# Constants / defaults
# ─────────────────────────────────────────────────────────────────────────────

CA_CA_CLASH_THRESHOLD = 3.5  # Å  — Ca²⁺/Ca²⁺ pairs closer than this clash
CA_O_CONTACT_CUTOFF = 4.0  # Å  — O-contact cutoff for Ca²⁺ quality score
CA_O_BOND = 2.5  # A — typical Ca²⁺–O bond length; used to remove ions with zero Ca-O Bonds.
DEFAULT_RESTRAINT_K = 1000.0  # kJ/mol/nm²
DEFAULT_MAX_ITER = 2000
OPENFF_FF = "openff-2.1.0"  # change to openff-2.0.0 if not installed

# Inline AMBER Ca2+ residue/force-field XML.
# Aqvist (1990) LJ parameters; charge +2.  Needed because amber14-all.xml
# only exposes Ca2+ inside water-model sub-files, not in vacuo.
_CA_ION_XML = (
    "<ForceField>\n"
    "  <AtomTypes>\n"
    '    <Type name="ca2_ion" class="CA2" element="Ca" mass="40.078"/>\n'
    "  </AtomTypes>\n"
    "  <Residues>\n"
    '    <Residue name="CA">\n'
    '      <Atom name="CA" type="ca2_ion" charge="2.0"/>\n'
    "    </Residue>\n"
    "  </Residues>\n"
    '  <NonbondedForce coulomb14scale="0.83333333" lj14scale="0.5">\n'
    '    <Atom type="ca2_ion" charge="2.0" sigma="0.24299" epsilon="0.50208"/>\n'
    "  </NonbondedForce>\n"
    "</ForceField>\n"
)

# CDZ SMILES (identical to run-CaM.sh)
CDZ_SMILES = "Clc1ccc(cc1)C(c2ccc(Cl)cc2)[n+]3ccn(C[C@H](OCc4ccc(Cl)cc4Cl)c5ccc(Cl)cc5Cl)c3"


# ─────────────────────────────────────────────────────────────────────────────
# § 0  Utilities
# ─────────────────────────────────────────────────────────────────────────────


def parse_rank_plddt(name: str) -> tuple[int, str] | None:
    """Extract (rank_int, plddt_str) from a NeuralPLexer filename."""
    m = re.search(r"rank(\d+)_plddt(\d+(?:\.\d+)?)", name)
    return (int(m.group(1)), m.group(2)) if m else None


def select_ca_ions(u: mda.Universe) -> mda.AtomGroup:
    """
    Select Ca²⁺ HETATM atoms.

    combine_outputs.py writes Ca²⁺ ions as:
      HETATM, resname 'CA ', chain Z, element Ca
    The selection 'resname CA and not protein' is the most reliable way to
    distinguish them from backbone Cα (which appear as 'protein and name CA').
    """
    return u.select_atoms("resname CA and not protein")


# ─────────────────────────────────────────────────────────────────────────────
# § 1  Ca²⁺ clash detection + resolution
# ─────────────────────────────────────────────────────────────────────────────


def resolve_ca_clashes(
    u: mda.Universe,
    clash_threshold: float = CA_CA_CLASH_THRESHOLD,
    o_cutoff: float = CA_O_CONTACT_CUTOFF,
) -> set[int]:
    """
    Return the set of Ca²⁺ residue IDs that should be removed.

    Algorithm
    ---------
    1. For every Ca²⁺/Ca²⁺ pair with distance < clash_threshold, count the
       number of oxygen atoms (all elements O, any residue) within o_cutoff Å
       of each ion.
    2. Process clashing pairs in ascending distance order (greediest first-fix).
    3. For each clash not yet resolved, remove the ion with *fewer* O contacts.
       Ties are broken by removing the first ion (lower residue ID).
    """
    ca_ions = select_ca_ions(u)
    if len(ca_ions) < 2:
        return set()

    ca_pos = ca_ions.positions.copy()  # (N, 3) Å
    ca_rids = [int(a.resid) for a in ca_ions]

    # Count O contacts per ion
    oxy = u.select_atoms("element O or name O*")
    oxy_pos = oxy.positions.copy() if len(oxy) else np.zeros((0, 3), dtype=np.float32)

    def n_o_contacts(ca_xyz: np.ndarray) -> int:
        if oxy_pos.shape[0] == 0:
            return 0
        return int(np.sum(np.linalg.norm(oxy_pos - ca_xyz, axis=1) < o_cutoff))

    o_cnt: dict[int, int] = {ca_rids[i]: n_o_contacts(ca_pos[i]) for i in range(len(ca_ions))}

    # Enumerate clashing pairs sorted by distance (ascending)
    clashes: list[tuple[float, int, int]] = []
    n = len(ca_ions)
    for i in range(n):
        for j in range(i + 1, n):
            d = float(np.linalg.norm(ca_pos[i] - ca_pos[j]))
            if d < clash_threshold:
                clashes.append((d, ca_rids[i], ca_rids[j]))
    clashes.sort()

    to_remove: set[int] = set()
    for d, ri, rj in clashes:
        if ri in to_remove or rj in to_remove:
            continue  # already resolved
        ci, cj = o_cnt.get(ri, 0), o_cnt.get(rj, 0)
        loser = ri if ci <= cj else rj
        winner = rj if loser == ri else ri
        to_remove.add(loser)
        print(
            f"      Clash {d:.2f} Å  →  removing Ca resid {loser:>4d} "
            f"({o_cnt.get(loser, 0):>2d} O-contacts)  |  "
            f"keeping  Ca resid {winner:>4d} "
            f"({o_cnt.get(winner, 0):>2d} O-contacts)"
        )

    return to_remove


def find_isolated_ca_ions(
    u: mda.Universe,
    bond_cutoff: float = CA_O_BOND,
) -> set[int]:
    """
    Return residue IDs of Ca²⁺ ions with no oxygen atom within ``bond_cutoff`` Å.
    Ions without any bonding-distance O are considered un-coordinated and removed.
    """
    ca_ions = select_ca_ions(u)
    if len(ca_ions) == 0:
        return set()

    oxy = u.select_atoms("element O or name O*")
    oxy_pos = oxy.positions.copy() if len(oxy) else np.zeros((0, 3), dtype=np.float32)

    isolated: set[int] = set()
    for atom in ca_ions:
        if oxy_pos.shape[0] == 0 or not np.any(np.linalg.norm(oxy_pos - atom.position, axis=1) < bond_cutoff):
            isolated.add(int(atom.resid))
            print(f"      Isolated Ca resid {int(atom.resid):>4d} — no O within {bond_cutoff} Å → removing")
    return isolated


# ─────────────────────────────────────────────────────────────────────────────
# § 2  CDZ molecule preparation
# ─────────────────────────────────────────────────────────────────────────────


def load_cdz_template_rdkit(sdf_path: Path) -> Chem.Mol:
    """
    Load the CDZ SDF template as a heavy-atom, sanitized RDKit Mol.
    Falls back to building from SMILES if the SDF cannot be parsed.
    """
    if sdf_path.exists():
        suppl = Chem.SDMolSupplier(str(sdf_path), sanitize=False, removeHs=False)
        mol = next(suppl, None)
        if mol is not None:
            try:
                mol = Chem.RemoveHs(mol, sanitize=False)  # strip explicit Hs with coords
                Chem.SanitizeMol(mol)
                return mol
            except Exception as exc:
                print(f"      [WARNING] SDF sanitization failed ({exc}); falling back to SMILES.")

    # SMILES fallback
    print("      [INFO] Building CDZ template from SMILES.")
    mol = Chem.MolFromSmiles(CDZ_SMILES)
    if mol is None:
        raise RuntimeError("Cannot build CDZ template from SMILES — check CDZ_SMILES.")
    AllChem.EmbedMolecule(mol, AllChem.ETKDGv3())
    return mol


def make_cdz_off_mol(
    template_mol: Chem.Mol,
    heavy_coords_ang: np.ndarray,
) -> OFFMolecule:
    """
    Clone the CDZ heavy-atom template, place the supplied coordinates from the
    complex PDB, add H atoms with 3-D geometry, and return an OpenFF Molecule.

    Assumes the heavy-atom ordering in ``heavy_coords_ang`` matches
    ``template_mol`` (preserved by combine_outputs.py → MDAnalysis write).

    Parameters
    ----------
    template_mol :
        Heavy-atom RDKit Mol loaded from 85H_ideal.sdf.
    heavy_coords_ang :
        (N_heavy, 3) ndarray of positions in Ångström from the combined PDB.
    """
    n_t = template_mol.GetNumAtoms()
    n_p = heavy_coords_ang.shape[0]
    if n_t != n_p:
        raise ValueError(
            f"CDZ template has {n_t} heavy atoms but the complex provides {n_p}. "
            "Atom-count mismatch — cannot assign PDB coordinates to template. "
            "Ensure 85H_ideal.sdf and the NeuralPLexer output use the same atom ordering."
        )

    # Clone template and replace the conformer with PDB coordinates
    rw = Chem.RWMol(template_mol)
    conf = rw.GetConformer()
    for i, (x, y, z) in enumerate(heavy_coords_ang.tolist()):
        conf.SetAtomPosition(i, (float(x), float(y), float(z)))

    # Add H atoms with 3-D coordinates derived from the heavy-atom geometry
    mol_h = Chem.AddHs(rw.GetMol(), addCoords=True)

    return OFFMolecule.from_rdkit(mol_h, allow_undefined_stereo=True)


# ─────────────────────────────────────────────────────────────────────────────
# § 3  Ca²⁺ OpenMM topology builder
# ─────────────────────────────────────────────────────────────────────────────


def build_ca_openmm_topology(
    ca_positions_ang: np.ndarray,
) -> tuple[app.Topology, unit.Quantity]:
    """
    Build a minimal OpenMM Topology for N Ca²⁺ ions.

    Each ion is a single-atom residue named 'CA' with element Calcium, which
    matches the residue template in amber14-all.xml for Ca²⁺.
    All ions are placed on chain 'I' (Ions).
    """
    topo = app.Topology()
    chain = topo.addChain(id="I")
    element = app.Element.getBySymbol("Ca")
    vecs_nm: list[mm.Vec3] = []

    for pos in ca_positions_ang:
        res = topo.addResidue("CA", chain)
        topo.addAtom("CA", element, res)
        vecs_nm.append(mm.Vec3(*(pos / 10.0)))  # Å → nm

    return topo, vecs_nm * unit.nanometer


# ─────────────────────────────────────────────────────────────────────────────
# § 4  Full system builder
# ─────────────────────────────────────────────────────────────────────────────


def build_system(
    u: mda.Universe,
    ca_to_remove: set[int],
    cdz_template_sdf: Path,
    *,
    cached_template_rdkit: "Chem.Mol | None" = None,
    cached_system_generator: "SystemGenerator | None" = None,
) -> tuple[app.Topology, unit.Quantity, mm.System, list[int], list[int]]:
    """
    Build the combined OpenMM topology, positions, and System for minimisation.

    Component breakdown
    -------------------
    Protein (H added by PDBFixer pH 7)  →  amber14-all.xml (ff14SB)
    Ca²⁺ ions (created from MDAnalysis) →  amber14-all.xml (AMBER Ca²⁺)
    CDZ ligands (from OpenFF topology)  →  OpenFF Sage (openff-2.1.0)

    Returns
    -------
    topology        : Combined OpenMM Topology.
    positions       : Positions Quantity (nm).
    system          : OpenMM System (no restraints added yet).
    ca_ion_indices  : Atom indices in topology for Ca²⁺ ions.
    calpha_indices  : Atom indices in topology for protein Cα carbons.
    """

    # ── 4a. Protein: PDBFixer ── ──────────────────────────────────────────
    prot_ag = u.select_atoms("protein")
    if len(prot_ag) == 0:
        raise ValueError("No protein atoms found in the complex PDB.")

    tmp_fd, tmp_prot = tempfile.mkstemp(suffix=".pdb")
    os.close(tmp_fd)
    try:
        prot_ag.write(tmp_prot)
        fixer = PDBFixer(filename=tmp_prot)
        fixer.findMissingResidues()
        fixer.findNonstandardResidues()
        fixer.replaceNonstandardResidues()
        fixer.findMissingAtoms()
        fixer.addMissingAtoms()
        fixer.addMissingHydrogens(7.4)  # pH 7 protonation
    finally:
        os.unlink(tmp_prot)

    prot_buf = io.StringIO()
    app.PDBFile.writeFile(fixer.topology, fixer.positions, prot_buf)
    prot_buf.seek(0)
    prot_omm = app.PDBFile(prot_buf)

    modeller = app.Modeller(prot_omm.topology, prot_omm.positions)

    # ── 4b. Ca²⁺ ions ────────────────────────────────────────────────────
    ca_ions = select_ca_ions(u)
    surviving = [a for a in ca_ions if int(a.resid) not in ca_to_remove]

    if surviving:
        ca_pos_ang = np.array([a.position for a in surviving], dtype=np.float64)
        ca_topo, ca_pos_nm = build_ca_openmm_topology(ca_pos_ang)
        modeller.add(ca_topo, ca_pos_nm)

    # ── 4c. CDZ ligands ───────────────────────────────────────────────────
    cdz_heavy = u.select_atoms("resname CDZ and not (name H* or element H)")
    cdz_resids = sorted(set(cdz_heavy.resids.tolist()))
    cdz_off_mols: list[OFFMolecule] = []

    if cdz_resids:
        _tmpl = cached_template_rdkit if cached_template_rdkit is not None \
                else load_cdz_template_rdkit(cdz_template_sdf)

        for resid in cdz_resids:
            atoms = cdz_heavy.select_atoms(f"resid {resid}")
            coords_ang = atoms.positions.copy()

            try:
                off_mol = make_cdz_off_mol(_tmpl, coords_ang)
            except ValueError as exc:
                print(f"      [WARNING] CDZ resid {resid}: {exc}")
                continue

            cdz_off_mols.append(off_mol)

            # Convert OpenFF topology → OpenMM topology + positions
            off_topo = OFFTopology.from_molecules([off_mol])
            omm_topo = off_topo.to_openmm()

            # Positions: OpenFF Å → OpenMM nm
            conf_ang = off_mol.conformers[0].m_as(off_unit.angstrom)  # (N, 3) numpy
            omm_pos = [mm.Vec3(*(row / 10.0)) for row in conf_ang] * unit.nanometer

            modeller.add(omm_topo, omm_pos)

    # ── 4d. SystemGenerator ──────────────────────────────────────────────
    # Pass one unique CDZ template (all copies are chemically identical).
    unique_mols: list[OFFMolecule] = [cdz_off_mols[0]] if cdz_off_mols else []

    if cached_system_generator is not None:
        sg = cached_system_generator
        modeller.topology.setPeriodicBoxVectors(None)
        system = sg.create_system(modeller.topology, molecules=unique_mols)
        for force in system.getForces():
            if isinstance(force, mm.NonbondedForce):
                force.setNonbondedMethod(mm.NonbondedForce.NoCutoff)
    else:
        # Write inline Ca2+ XML to a temp file; amber14-all.xml only exposes Ca2+
        # inside water-model sub-files so we supply the template explicitly.
        ca_xml_fd, ca_xml_path = tempfile.mkstemp(suffix=".xml")
        try:
            os.write(ca_xml_fd, _CA_ION_XML.encode())
            os.close(ca_xml_fd)

            sg = SystemGenerator(
                forcefields=["amber14-all.xml", ca_xml_path],
                small_molecule_forcefield=OPENFF_FF,
                molecules=unique_mols,
                forcefield_kwargs={
                    "constraints": None,
                    "removeCMMotion": False,
                },
                nonperiodic_forcefield_kwargs={
                    "nonbondedMethod": app.NoCutoff,
                },
                cache=None,
            )
            # Clear box before create_system so SystemGenerator picks
            # nonperiodic_forcefield_kwargs (NoCutoff) not periodic ones.
            modeller.topology.setPeriodicBoxVectors(None)
            system = sg.create_system(modeller.topology, molecules=unique_mols)
            # Belt-and-braces: force NoCutoff on every NonbondedForce in case
            # any sub-force-field re-introduced a cutoff.
            for force in system.getForces():
                if isinstance(force, mm.NonbondedForce):
                    force.setNonbondedMethod(mm.NonbondedForce.NoCutoff)
        finally:
            os.unlink(ca_xml_path)

    # ── 4e. Identify Cα and Ca²⁺ atom indices ────────────────────────────
    # Ca²⁺ ions  → element symbol 'Ca'  (added in § 4b as element Calcium)
    # Protein Cα → element symbol 'C', atom name 'CA', in amino-acid residue
    calpha_indices: list[int] = []
    ca_ion_indices: list[int] = []

    for idx, atom in enumerate(modeller.topology.atoms()):
        el = atom.element
        if el is None:
            continue
        if el.symbol == "Ca":
            ca_ion_indices.append(idx)
        elif el.symbol == "C" and atom.name == "CA":
            calpha_indices.append(idx)

    return (
        modeller.topology,
        modeller.positions,
        system,
        ca_ion_indices,
        calpha_indices,
    )


# ─────────────────────────────────────────────────────────────────────────────
# § 5  Positional restraints
# ─────────────────────────────────────────────────────────────────────────────


def add_positional_restraints(
    system: mm.System,
    positions: unit.Quantity,
    indices: list[int],
    k: float,  # kJ/mol/nm²
) -> None:
    """
    Add harmonic positional restraints to the specified atom indices.

    The restraint energy is:
        E = k * [ (x-x₀)² + (y-y₀)² + (z-z₀)² ]

    Reference positions (x₀, y₀, z₀) are taken from the current positions.
    """
    if not indices:
        return

    force = mm.CustomExternalForce("k * ((x - x0)^2 + (y - y0)^2 + (z - z0)^2)")
    force.addGlobalParameter("k", k * unit.kilojoules_per_mole / unit.nanometer**2)
    force.addPerParticleParameter("x0")
    force.addPerParticleParameter("y0")
    force.addPerParticleParameter("z0")

    pos_nm = positions.value_in_unit(unit.nanometer)
    for idx in indices:
        x0, y0, z0 = pos_nm[idx]
        force.addParticle(idx, [x0, y0, z0])

    system.addForce(force)


# ─────────────────────────────────────────────────────────────────────────────
# § 6  Minimisation
# ─────────────────────────────────────────────────────────────────────────────


def run_minimisation(
    topology: app.Topology,
    positions: unit.Quantity,
    system: mm.System,
    max_iterations: int,
) -> mm.State:
    """
    Run in-vacuo L-BFGS energy minimisation.

    Platform preference: CUDA → OpenCL → CPU.
    The Langevin integrator is required by OpenMM's Simulation API but is
    never stepped — it acts only as a placeholder for minimisation.
    """
    integrator = mm.LangevinMiddleIntegrator(
        300 * unit.kelvin,
        1.0 / unit.picosecond,
        0.002 * unit.picoseconds,
    )

    simulation: app.Simulation | None = None
    platform_errors: list[str] = []
    for platform_name in ("CUDA", "OpenCL", "CPU"):
        try:
            platform = mm.Platform.getPlatformByName(platform_name)
            simulation = app.Simulation(topology, system, integrator, platform)
            print(f"      Platform   : {platform_name}")
            break
        except Exception as exc:
            platform_errors.append(f"{platform_name}: {exc}")
            continue

    if simulation is None:
        for msg in platform_errors:
            print(f"      [PLATFORM FAIL] {msg}", file=sys.stderr)
        raise RuntimeError("No usable OpenMM platform found. See PLATFORM FAIL lines above.")

    simulation.context.setPositions(positions)

    e0 = (
        simulation.context.getState(getEnergy=True)
        .getPotentialEnergy()
        .value_in_unit(unit.kilojoules_per_mole)
    )
    print(f"      Initial PE : {e0:>14.1f}  kJ/mol")

    simulation.minimizeEnergy(maxIterations=max_iterations, tolerance=1.0)

    state = simulation.context.getState(getEnergy=True, getPositions=True)
    ef = state.getPotentialEnergy().value_in_unit(unit.kilojoules_per_mole)
    print(f"      Final PE   : {ef:>14.1f}  kJ/mol  (ΔE = {ef - e0:+.1f} kJ/mol)")

    return state


# ─────────────────────────────────────────────────────────────────────────────
# § 7  Output PDB writer
# ─────────────────────────────────────────────────────────────────────────────


def write_pdb(
    topology: app.Topology,
    positions: unit.Quantity,
    out_path: Path,
) -> None:
    """
    Write a PDB file.

    OpenMM's PDBFile.writeFile() automatically emits CONECT records for all
    bonds involving atoms in non-standard (HETATM) residues — i.e. CDZ bonds
    will appear as CONECT records without any extra work.
    """
    with open(str(out_path), "w") as fh:
        app.PDBFile.writeFile(topology, positions, fh, keepIds=True)


# ─────────────────────────────────────────────────────────────────────────────
# § 8  Per-frame pipeline
# ─────────────────────────────────────────────────────────────────────────────


def process_frame(
    pdb_path: Path,
    cdz_template_sdf: Path,
    output_dir: Path,
    *,
    ca_clash_threshold: float,
    ca_o_cutoff: float,
    restraint_k: float,
    max_iterations: int,
    cached_template_rdkit: "Chem.Mol | None" = None,
    cached_system_generator: "SystemGenerator | None" = None,
) -> bool:
    """
    Run the full minimisation pipeline for one complex PDB frame.
    Returns True on success, False on any fatal error.
    """
    parsed = parse_rank_plddt(pdb_path.name)
    if parsed is None:
        print(f"  [SKIP] Cannot parse rank/pLDDT from '{pdb_path.name}'.")
        return False
    rank, plddt = parsed

    print(f"\n{'─' * 74}")
    print(f"  rank {rank:>3d}  │  pLDDT {plddt:<12s}  │  {pdb_path.name}")
    print(f"{'─' * 74}")

    u = mda.Universe(str(pdb_path))

    n_ca_init = len(set(select_ca_ions(u).resids.tolist()))
    n_cdz_init = len(set(u.select_atoms("resname CDZ").resids.tolist()))
    print(f"  Input composition : {n_ca_init} Ca²⁺  │  {n_cdz_init} CDZ")

    # ── Step 1: Ca²⁺ filtering (isolated + clash) ───────────────────────
    print("\n  [1/4] Ca²⁺ filtering ...")

    # 1a. Remove ions with no bonding-distance O (CA_O_BOND Å)
    ca_isolated = find_isolated_ca_ions(u, CA_O_BOND)
    if ca_isolated:
        print(f"      Removed {len(ca_isolated)} isolated Ca²⁺ ion(s) (no O within {CA_O_BOND} Å).")
    else:
        print("      No isolated Ca²⁺ ions.")

    # 1b. Clash detection among all ions (isolated will be filtered in build_system)
    ca_clashes = resolve_ca_clashes(u, ca_clash_threshold, ca_o_cutoff)
    # Exclude already-isolated ions from clash reporting
    ca_clashes -= ca_isolated
    if ca_clashes:
        print(f"      Removed {len(ca_clashes)} clashing Ca²⁺ ion(s).")
    else:
        print("      No Ca²⁺/Ca²⁺ clashes detected.")

    ca_to_remove = ca_isolated | ca_clashes
    n_ca_final = n_ca_init - len(ca_to_remove)
    n_cdz_final = n_cdz_init  # CDZ count unchanged by removal

    # ── Step 2: Build system ────────────────────────────────────────────
    print("\n  [2/4] Building OpenMM system (ff14SB + OpenFF Sage) ...")
    try:
        topo, positions, system, ca_ion_idxs, calpha_idxs = build_system(
            u, ca_to_remove, cdz_template_sdf,
            cached_template_rdkit=cached_template_rdkit,
            cached_system_generator=cached_system_generator,
        )
    except Exception as exc:
        print(f"  [ERROR] System build failed: {exc}")
        traceback.print_exc(file=sys.stderr)
        return False

    print(
        f"      Atoms {topo.getNumAtoms():<6d}  │  "
        f"Bonds {topo.getNumBonds():<6d}  │  "
        f"Restrained: {len(calpha_idxs)} Cα + {len(ca_ion_idxs)} Ca²⁺"
    )

    # ── Step 3: Positional restraints ───────────────────────────────────
    print("\n  [3/4] Adding positional restraints ...")
    print(f"      k = {restraint_k} kJ/mol/nm²  →  protein Cα + Ca²⁺ ions")
    print("      CDZ ligands are unrestrained (free to move)")
    restrained = sorted(set(calpha_idxs + ca_ion_idxs))
    add_positional_restraints(system, positions, restrained, restraint_k)

    # ── Step 4: Minimise ────────────────────────────────────────────────
    print("\n  [4/4] Running in-vacuo minimisation ...")
    try:
        final_state = run_minimisation(topo, positions, system, max_iterations)
    except Exception as exc:
        print(f"  [ERROR] Minimisation failed: {exc}")
        traceback.print_exc(file=sys.stderr)
        return False

    # ── Write output ────────────────────────────────────────────────────
    out_name = f"complex_rank{rank}_plddt{plddt}_ca{n_ca_final}_cdz{n_cdz_final}_minimised.pdb"
    out_path = output_dir / out_name
    write_pdb(topo, final_state.getPositions(), out_path)
    print(f"\n  ✓  Written → {out_path.name}")
    return True


# ─────────────────────────────────────────────────────────────────────────────
# § 9  CLI entry point
# ─────────────────────────────────────────────────────────────────────────────


def main() -> None:
    global OPENFF_FF
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "--input-dir",
        required=True,
        help="Directory containing complex_rank*.pdb files from combine_outputs.py.",
    )
    parser.add_argument(
        "--ligand-sdf",
        required=True,
        help="Path to 85H_ideal.sdf (CDZ template; provides atom connectivity).",
    )
    parser.add_argument(
        "--output-dir",
        default=None,
        help="Output directory (default: <input-dir>/minimised/).",
    )
    parser.add_argument(
        "--ca-clash-threshold",
        type=float,
        default=CA_CA_CLASH_THRESHOLD,
        help=f"Ca²⁺/Ca²⁺ clash cutoff in Å (default {CA_CA_CLASH_THRESHOLD}).",
    )
    parser.add_argument(
        "--ca-o-cutoff",
        type=float,
        default=CA_O_CONTACT_CUTOFF,
        help=f"Oxygen-contact cutoff for Ca²⁺ quality scoring in Å "
        f"(default {CA_O_CONTACT_CUTOFF}).",
    )
    parser.add_argument(
        "--restraint-k",
        type=float,
        default=DEFAULT_RESTRAINT_K,
        help=f"Force constant for Cα / Ca²⁺ positional restraints "
        f"in kJ/mol/nm² (default {DEFAULT_RESTRAINT_K}).",
    )
    parser.add_argument(
        "--max-iterations",
        type=int,
        default=DEFAULT_MAX_ITER,
        help=f"Maximum L-BFGS minimisation steps (default {DEFAULT_MAX_ITER}).",
    )
    parser.add_argument(
        "--top-n",
        type=int,
        default=None,
        help="Process only the top N frames ranked by pLDDT rank index.",
    )
    parser.add_argument(
        "--openff-ff",
        default=OPENFF_FF,
        help=f"OpenFF force field string (default '{OPENFF_FF}').",
    )
    args = parser.parse_args()

    # Override global constant if user supplied a different FF
    OPENFF_FF = args.openff_ff

    input_dir = Path(args.input_dir).resolve()
    output_dir = Path(args.output_dir).resolve() if args.output_dir else input_dir / "minimised"
    ligand_sdf = Path(args.ligand_sdf).resolve()

    if not input_dir.is_dir():
        sys.exit(f"[ERROR] --input-dir not found: {input_dir}")
    if not ligand_sdf.exists():
        sys.exit(f"[ERROR] --ligand-sdf not found: {ligand_sdf}")

    output_dir.mkdir(parents=True, exist_ok=True)

    # Discover and sort frames by rank
    def _rank_key(p: Path) -> int:
        result = parse_rank_plddt(p.name)
        return result[0] if result is not None else 0

    pdb_files = sorted(
        (p for p in input_dir.glob("complex_rank*.pdb") if parse_rank_plddt(p.name)),
        key=_rank_key,
    )
    if not pdb_files:
        sys.exit(f"[ERROR] No complex_rank*.pdb files found in {input_dir}")

    if args.top_n is not None:
        pdb_files = pdb_files[: args.top_n]

    # ── Banner ────────────────────────────────────────────────────────────
    print(f"\n{'═' * 74}")
    print("  NeuralPLexer Ensemble In-Vacuo Constrained Minimisation")
    print(f"{'═' * 74}")
    print(f"  Frames to process  : {len(pdb_files)}")
    print(f"  Input dir          : {input_dir}")
    print(f"  Output dir         : {output_dir}")
    print(f"  CDZ template       : {ligand_sdf}")
    print(f"  Ca clash threshold : {args.ca_clash_threshold} Å")
    print(f"  Ca O-contact cutoff: {args.ca_o_cutoff} Å")
    print(f"  Restraint k (Cα/Ca): {args.restraint_k} kJ/mol/nm²")
    print(f"  Max iterations     : {args.max_iterations}")
    print(f"  OpenFF FF          : {OPENFF_FF}")
    print(f"{'═' * 74}")

    # ── Pre-build CDZ template + SystemGenerator (cached across frames) ──────
    print("  Pre-building CDZ ligand cache (AM1-BCC charges) ...")
    cached_template_rdkit = load_cdz_template_rdkit(ligand_sdf)
    _proto_h = Chem.AddHs(cached_template_rdkit, addCoords=True)
    cdz_prototype = OFFMolecule.from_rdkit(_proto_h, allow_undefined_stereo=True)

    _ca_xml_fd, _ca_xml_path = tempfile.mkstemp(suffix=".xml")
    try:
        os.write(_ca_xml_fd, _CA_ION_XML.encode())
        os.close(_ca_xml_fd)
        cached_system_generator = SystemGenerator(
            forcefields=["amber14-all.xml", _ca_xml_path],
            small_molecule_forcefield=OPENFF_FF,
            molecules=[cdz_prototype],
            forcefield_kwargs={"constraints": None, "removeCMMotion": False},
            nonperiodic_forcefield_kwargs={"nonbondedMethod": app.NoCutoff},
            cache=None,
        )
    finally:
        os.unlink(_ca_xml_path)
    print("  CDZ cache ready.")

    n_ok = 0
    for pdb_path in pdb_files:
        try:
            ok = process_frame(
                pdb_path,
                ligand_sdf,
                output_dir,
                ca_clash_threshold=args.ca_clash_threshold,
                ca_o_cutoff=args.ca_o_cutoff,
                restraint_k=args.restraint_k,
                max_iterations=args.max_iterations,
                cached_template_rdkit=cached_template_rdkit,
                cached_system_generator=cached_system_generator,
            )
            if ok:
                n_ok += 1
        except Exception as exc:
            print(f"\n  [ERROR] Unhandled exception for {pdb_path.name}: {exc}")
            traceback.print_exc()

    print(f"\n{'═' * 74}")
    print(f"  Finished: {n_ok}/{len(pdb_files)} frames minimised  →  {output_dir}")
    print(f"{'═' * 74}\n")


if __name__ == "__main__":
    main()
