"""
This script extracts the per-replicate weights and predicted log Pf values 
generated by process_optimisation_results.py for the models selected by the 
different metrics in the score_models_ISO_TRI_BI.py script.

Specifically adapted for Example 3 (CrossValidationBV) which includes
bv_reg_value and bv_reg_function hyperparameters.

Script arguments:
    --processed-data-dir: Directory containing processed .npy files from process_optimisation_results.py
    --scores-csv: Path to the detailed model_scores.csv generated by score_models_ISO_TRI_BI.py
    --selection-csv: Path to the summary CSV generated by analyse_scores_mixed_linear_model.py
    --output-dir: Output directory. If omitted, creates 'selected_models' inside processed-data-dir.
    --datasplit-dir: Directory containing data splits (used for resolving effective split type).
    --config: Path to experiment config YAML.
    --absolute-paths: Interpret provided directories as absolute paths.

Output weights and Pfs are saved as npz files (replicate_number, data_dimensions) into organised subfolders.
"""

import argparse
import os
import sys

import numpy as np
import pandas as pd
from tqdm import tqdm

current_dir = os.path.dirname(os.path.abspath(__file__))
base_dir = os.path.abspath(os.path.join(current_dir, "../../../"))
sys.path.insert(0, base_dir)

from jaxent.examples.common import loading
from jaxent.examples.common.config import ExperimentConfig

ENSEMBLE_PATTERN = (
    r"(AF2_MSAss|AF2_filtered)_(mcMSE|MSE|Sigma_MSE)_(.+?)_split(\d+)"
    r"_maxent([\d.]+)_bvreg([\d.]+)_bvregfn([A-Za-z0-9]+)"
)


def _resolve_effective_split_type(run_split_type: str, datasplit_dir: str) -> str:
    """Return the datasplit directory name that actually exists for this run_split_type."""
    if "_cluster" in run_split_type:
        full_path = os.path.join(datasplit_dir, run_split_type)
        stripped = run_split_type.replace("_cluster", "")
        stripped_path = os.path.join(datasplit_dir, stripped)
        if os.path.exists(full_path):
            return run_split_type
        elif os.path.exists(stripped_path):
            return stripped
        return stripped
    return run_split_type


def main():
    parser = argparse.ArgumentParser(
        description="Extract best subset of JAX-ENT arrays for down-stream plotting."
    )
    parser.add_argument(
        "--processed-data-dir",
        required=True,
        help="Directory containing processed .npy files from process_optimisation_results.py",
    )
    parser.add_argument(
        "--scores-csv",
        required=True,
        help="Path to the model_scores.csv generated by score_models_ISO_TRI_BI.py",
    )
    parser.add_argument(
        "--selection-csv",
        required=True,
        help="Path to the model_selection_performance_summary.csv",
    )
    parser.add_argument(
        "--output-dir",
        default=None,
        help="Output directory. Defaults to 'selected_models' inside processed-data-dir.",
    )
    parser.add_argument(
        "--datasplit-dir",
        default="../fitting/jaxENT/_datasplits",
        help="Directory containing data splits (used to resolve cluster strings).",
    )
    parser.add_argument(
        "--config",
        default="../config.yaml",
        help="Path to experiment config YAML.",
    )
    parser.add_argument(
        "--absolute-paths",
        action="store_true",
        default=False,
        help="Interpret provided directories as absolute paths.",
    )
    args = parser.parse_args()

    script_dir = os.path.dirname(__file__)
    if args.absolute_paths:
        processed_data_dir = args.processed_data_dir
        datasplit_dir = args.datasplit_dir
        scores_csv_path = args.scores_csv
        selection_csv_path = args.selection_csv
    else:
        processed_data_dir = os.path.abspath(os.path.join(script_dir, args.processed_data_dir))
        datasplit_dir = os.path.abspath(os.path.join(script_dir, args.datasplit_dir))
        scores_csv_path = os.path.abspath(os.path.join(script_dir, args.scores_csv))
        selection_csv_path = os.path.abspath(os.path.join(script_dir, args.selection_csv))

    if args.output_dir:
        output_dir = (
            args.output_dir
            if args.absolute_paths
            else os.path.abspath(os.path.join(script_dir, args.output_dir))
        )
    else:
        basename = os.path.basename(processed_data_dir.rstrip("/"))
        output_dir = os.path.join(processed_data_dir, f"_extracted_{basename}")
    os.makedirs(output_dir, exist_ok=True)

    print(f"processed_data_dir: {processed_data_dir}")
    print(f"scores_csv_path:    {scores_csv_path}")
    print(f"selection_csv_path: {selection_csv_path}")
    print(f"output_dir:         {output_dir}")
    print("-" * 60)

    if not os.path.exists(scores_csv_path):
        raise FileNotFoundError(f"Scores CSV not found: {scores_csv_path}")
    if not os.path.exists(selection_csv_path):
        raise FileNotFoundError(f"Selection CSV not found: {selection_csv_path}")

    # Load CSVs
    scores_df = pd.read_csv(scores_csv_path)
    selection_df = pd.read_csv(selection_csv_path)

    # Convert split_idx to int just in case
    scores_df["split_idx"] = scores_df["split_idx"].astype(int)

    # First pass: catalog all arrays from processed data directories
    print("Cataloging processed runs...")
    all_run_info, _ = loading.load_processed_run_info(
        processed_data_dir, 
        ENSEMBLE_PATTERN,
        extra_group_names=["bv_reg_str", "bv_reg_fn"]
    )

    for r in all_run_info:
        r["bv_reg_value"] = float(r["bv_reg_str"])
        r["bv_reg_function"] = r["bv_reg_fn"]

    # Build an O(1) lookup: (ensemble, loss_name, split_type, split_idx, maxent_value, bv_reg_value, bv_reg_function) -> paths dict
    run_lookup = {}
    for r in all_run_info:
        eff_split_type = _resolve_effective_split_type(r["run_split_type"], datasplit_dir)
        key = (
            r["ensemble"],
            r["loss_name"],
            eff_split_type,
            int(r["split_idx"]),
            float(r["maxent_value"]),
            float(r["bv_reg_value"]),
            r["bv_reg_function"],
        )
        run_lookup[key] = r

    # Determine grouping cols for selection
    possible_group_cols = ["ensemble", "split_type", "loss_function", "bv_reg_function"]
    group_cols = [c for c in possible_group_cols if c in scores_df.columns]

    print("Extracting optimal slices based on selection criteria...")
    # Loop over all requested metrics and directions
    for _, sel_row in tqdm(selection_df.drop_duplicates(subset=["score_metric", "direction"]).iterrows()):
        metric = sel_row["score_metric"]
        direction = sel_row["direction"]

        if metric not in scores_df.columns:
            print(f"WARNING: Metric {metric} not found in scores_csv. Skipping.")
            continue

        metric_dir = os.path.join(output_dir, f"{metric}_{direction}")
        os.makedirs(metric_dir, exist_ok=True)

        grouped = scores_df.groupby(group_cols)
        for group_keys, group_df in grouped:
            if not isinstance(group_keys, tuple):
                group_keys = (group_keys,)
            group_dict = dict(zip(group_cols, group_keys))

            ens = group_dict["ensemble"]
            lf = group_dict.get("loss_function", "All")
            st = group_dict["split_type"]
            bv_reg = group_dict.get("bv_reg_function", "")

            # Identify the num_replicates for this group
            max_idx = group_df["split_idx"].max()
            if pd.isna(max_idx):
                continue
            num_replicates = int(max_idx) + 1

            agg_frame_weights = []
            agg_pred_ln_pf = []

            for idx in range(num_replicates):
                rep_df = group_df[group_df["split_idx"] == idx].dropna(subset=[metric])
                if rep_df.empty:
                    print(f"WARNING: No valid metric '{metric}' for {ens} {lf} {st} replicate {idx}")
                    agg_frame_weights.append(None)
                    agg_pred_ln_pf.append(None)
                    continue

                if direction == "min":
                    best_row_idx = rep_df[metric].idxmin()
                else:
                    best_row_idx = rep_df[metric].idxmax()
                
                best_row = rep_df.loc[best_row_idx]
                m_val = float(best_row["maxent_value"])
                bv_val = float(best_row["bv_reg_value"])
                bv_fn  = best_row["bv_reg_function"]
                c_val  = float(best_row["convergence_value"])

                lkp_key = (ens, lf, st, idx, m_val, bv_val, bv_fn)
                if lkp_key not in run_lookup:
                    print(f"WARNING: Paths not found for run {lkp_key} (Replicate {idx})")
                    agg_frame_weights.append(None)
                    agg_pred_ln_pf.append(None)
                    continue
                
                paths = run_lookup[lkp_key]
                full_run_path = paths.get("full_run_path")
                weights_path = os.path.join(full_run_path, "frame_weights.npy") if full_run_path else None
                ln_pf_path = os.path.join(full_run_path, "pred_ln_pf.npy") if full_run_path else None
                conv_path = os.path.join(full_run_path, "convergence_thresholds.txt") if full_run_path else None

                # Find the correct array index based on convergence_value
                convergence_index = -1
                if conv_path and os.path.exists(conv_path):
                    with open(conv_path, "r") as f:
                        lines = [line.strip() for line in f if line.strip()]
                    for i, line in enumerate(lines):
                        try:
                            # Safely handle 'state_X' or float values
                            if line.startswith("state_"):
                                val = float(line.split("_")[1])
                            else:
                                val = float(line)
                            
                            # allow some floating point tolerance if numeric
                            if abs(val - c_val) < 1e-9:
                                convergence_index = i
                                break
                        except ValueError:
                            pass
                
                if convergence_index == -1:
                    print(f"WARNING: Convergence value {c_val} not found in {conv_path}")
                    agg_frame_weights.append(None)
                    agg_pred_ln_pf.append(None)
                    continue

                if weights_path and os.path.exists(weights_path):
                    w_arr = np.load(weights_path)
                    if convergence_index < w_arr.shape[0]:
                        agg_frame_weights.append(w_arr[convergence_index])
                    else:
                        print(f"WARNING: IndexError accessing conv index {convergence_index} in {weights_path} with shape {w_arr.shape}")
                        agg_frame_weights.append(None)
                else:
                    agg_frame_weights.append(None)

                if ln_pf_path and os.path.exists(ln_pf_path):
                    pf_arr = np.load(ln_pf_path)
                    if convergence_index < pf_arr.shape[0]:
                        agg_pred_ln_pf.append(pf_arr[convergence_index])
                    else:
                        print(f"WARNING: IndexError accessing conv index {convergence_index} in {ln_pf_path} with shape {pf_arr.shape}")
                        agg_pred_ln_pf.append(None)
                else:
                    agg_pred_ln_pf.append(None)

            # Reconstruct and mask None
            try:
                # Provide a consistent filler array if one replicate fails, or just stack what we have
                # If some are None, we pad with NaNs matching the shape of the first valid element.
                first_valid_w = next((x for x in agg_frame_weights if x is not None), None)
                first_valid_pf = next((x for x in agg_pred_ln_pf if x is not None), None)

                if first_valid_w is not None:
                    final_weights = np.stack([
                        x if x is not None else np.full_like(first_valid_w, np.nan) 
                        for x in agg_frame_weights
                    ])
                else:
                    final_weights = np.array([])

                if first_valid_pf is not None:
                    final_pfs = np.stack([
                        x if x is not None else np.full_like(first_valid_pf, np.nan) 
                        for x in agg_pred_ln_pf
                    ])
                else:
                    final_pfs = np.array([])
                
                save_name = f"{ens}_{lf}_{st}"
                if bv_reg:
                    save_name += f"_{bv_reg}"
                
                out_path = os.path.join(metric_dir, f"{save_name}_selected.npz")
                np.savez(
                    out_path,
                    frame_weights=final_weights,
                    pred_ln_pf=final_pfs
                )
            except Exception as e:
                print(f"ERROR saving stacked arrays for {group_dict}: {e}")

    print("Extraction script complete.")


if __name__ == "__main__":
    main()
