"""Shared-rate mixture fitting for diagnostic HDX uptake-curve analysis.

This module deliberately models peptide-level kinetic heterogeneity.  Its covariance
objects are fit uncertainty and across-peptide score heterogeneity; neither is a
conformational covariance inferred from experimental mean curves.
"""

from __future__ import annotations

from dataclasses import dataclass
from collections.abc import Sequence

import jax
import jax.numpy as jnp
import numpy as np
from scipy.optimize import minimize
from sklearn.covariance import LedoitWolf

jax.config.update("jax_enable_x64", True)


@dataclass(frozen=True)
class RateMixtureFit:
    n_components: int
    shrinkage: float
    rates: np.ndarray
    weights: np.ndarray
    predicted: np.ndarray
    parameters: np.ndarray
    objective: float
    rmse: float
    success: bool
    message: str
    iterations: int
    gradient_norm: float


@dataclass(frozen=True)
class HessianUncertainty:
    parameter_covariance: np.ndarray
    joint_weight_covariance: np.ndarray
    conditional_weight_covariance: np.ndarray
    rate_covariance: np.ndarray
    curve_covariance: np.ndarray
    residual_variance: float
    condition_number: float
    valid: bool


@dataclass(frozen=True)
class ModelSelectionResult:
    selected_components: int
    selected_shrinkage: float
    rows: tuple[dict[str, float | int], ...]


@dataclass(frozen=True)
class JacobianDiagnostics:
    n_observations: int
    n_parameters: int
    numerical_rank: int
    effective_rank: float
    condition_number: float
    smallest_relative_singular_value: float


def rate_distribution_summaries(fit: RateMixtureFit) -> dict[str, np.ndarray]:
    """Basis-robust peptide summaries of a fitted discrete rate distribution.

    The final mixture column is unresolved mass slower than the experimental
    window, not a literal non-exchanging amide population.  Raw component
    weights remain available on ``fit`` but should not be compared directly
    when independently fitted rate grids move.
    """

    rates = np.asarray(fit.rates, dtype=float)
    weights = np.asarray(fit.weights, dtype=float)
    if rates.ndim != 1 or weights.ndim != 2 or weights.shape[1] != len(rates) + 1:
        raise ValueError("fit rates and weights are inconsistent")
    if np.any(rates <= 0) or np.any(weights < 0):
        raise ValueError("rates must be positive and weights non-negative")
    amplitude = weights[:, :-1].sum(axis=1)
    conditional = np.divide(
        weights[:, :-1],
        amplitude[:, None],
        out=np.zeros_like(weights[:, :-1]),
        where=amplitude[:, None] > 0,
    )
    log_rates = np.log(rates)
    mean = conditional @ log_rates
    variance = np.sum(conditional * (log_rates[None, :] - mean[:, None]) ** 2, axis=1)
    cumulative = np.cumsum(conditional, axis=1)

    def quantile(probability: float) -> np.ndarray:
        indices = np.argmax(cumulative >= probability, axis=1)
        result = log_rates[indices]
        result[amplitude <= 0] = np.nan
        return result

    mean[amplitude <= 0] = np.nan
    variance[amplitude <= 0] = np.nan
    return {
        "exchanging_amplitude": amplitude,
        "unresolved_slow_fraction": weights[:, -1],
        "mean_log_rate": mean,
        "sd_log_rate": np.sqrt(np.maximum(variance, 0.0)),
        "log_rate_q10": quantile(0.10),
        "log_rate_q50": quantile(0.50),
        "log_rate_q90": quantile(0.90),
    }


def rate_bounds(times: np.ndarray) -> tuple[float, float]:
    times = np.asarray(times, float)
    if times.ndim != 1 or np.any(times <= 0):
        raise ValueError("times must be a positive one-dimensional array")
    return 0.1 / float(times.max()), 10.0 / float(times.min())


def uptake_basis(times: np.ndarray, rates: np.ndarray) -> np.ndarray:
    times = np.asarray(times, float)
    rates = np.asarray(rates, float)
    return 1.0 - np.exp(-times[:, None] * rates[None, :])


def predict_uptake(times: np.ndarray, rates: np.ndarray, weights: np.ndarray) -> np.ndarray:
    """Return peptide x time uptake; the last weight is the zero-rate fraction."""
    weights = np.asarray(weights, float)
    if weights.shape[-1] != len(rates) + 1:
        raise ValueError("weights must contain K exchanging fractions plus one zero-rate fraction")
    return weights[..., :-1] @ uptake_basis(times, rates).T


def _decode_jax(
    parameters: jax.Array,
    n_peptides: int,
    n_components: int,
    lower: float,
    upper: float,
) -> tuple[jax.Array, jax.Array]:
    rate_logits = parameters[:n_components]
    peptide_logits = parameters[n_components:].reshape(n_peptides, n_components)
    # K ordered positions are generated by K+1 positive gaps spanning log-rate space.
    gaps = jax.nn.softmax(jnp.concatenate((rate_logits, jnp.zeros(1))))
    log_rates = jnp.log(lower) + jnp.cumsum(gaps[:-1]) * (jnp.log(upper) - jnp.log(lower))
    rates = jnp.exp(log_rates)
    weights = jax.nn.softmax(
        jnp.concatenate((peptide_logits, jnp.zeros((n_peptides, 1))), axis=1), axis=1
    )
    return rates, weights


def decode_parameters(
    parameters: np.ndarray,
    n_peptides: int,
    n_components: int,
    bounds: tuple[float, float],
) -> tuple[np.ndarray, np.ndarray]:
    rates, weights = _decode_jax(
        jnp.asarray(parameters), n_peptides, n_components, bounds[0], bounds[1]
    )
    return np.asarray(rates), np.asarray(weights)


def _objective_factory(
    curves: np.ndarray,
    times: np.ndarray,
    n_components: int,
    shrinkage: float,
    time_mask: np.ndarray,
):
    curves_j = jnp.asarray(curves)
    times_j = jnp.asarray(times)
    mask_j = jnp.asarray(time_mask, dtype=bool)
    lower, upper = rate_bounds(times)
    n_peptides = curves.shape[0]

    def objective(parameters: jax.Array) -> jax.Array:
        rates, weights = _decode_jax(parameters, n_peptides, n_components, lower, upper)
        basis = 1.0 - jnp.exp(-times_j[:, None] * rates[None, :])
        predicted = weights[:, :-1] @ basis.T
        residual = predicted[:, mask_j] - curves_j[:, mask_j]
        mean_weights = jnp.mean(weights, axis=0, keepdims=True)
        penalty = jnp.mean((weights - mean_weights) ** 2)
        return 0.5 * jnp.mean(residual**2) + shrinkage * penalty

    return objective


def _initial_parameters(
    curves: np.ndarray, times: np.ndarray, n_components: int, seed: int
) -> np.ndarray:
    rng = np.random.default_rng(seed)
    n_peptides = curves.shape[0]
    # Equal log-rate gaps and approximately equal kinetic fractions are a stable base start.
    base = np.zeros(n_components * (n_peptides + 1), float)
    amplitude = np.clip(curves[:, -1], 1e-3, 1 - 1e-3)
    exchanging = np.repeat(amplitude[:, None] / n_components, n_components, axis=1)
    immobile = 1.0 - amplitude[:, None]
    base[n_components:] = np.log(exchanging / immobile).reshape(-1)
    if seed:
        base += rng.normal(0.0, 0.2, size=base.shape)
    return base


def fit_shared_rate_mixture(
    curves: np.ndarray,
    times: np.ndarray,
    n_components: int,
    shrinkage: float = 0.0,
    *,
    train_time_mask: np.ndarray | None = None,
    starts: int = 20,
    seed: int = 1729,
    maxiter: int = 1000,
) -> RateMixtureFit:
    curves = np.asarray(curves, float)
    times = np.asarray(times, float)
    if curves.ndim != 2 or curves.shape[1] != len(times):
        raise ValueError("curves must have shape (peptides, timepoints)")
    if n_components < 1:
        raise ValueError("n_components must be positive")
    if np.any(~np.isfinite(curves)):
        raise ValueError("curves must be finite")
    mask = np.ones(len(times), bool) if train_time_mask is None else np.asarray(train_time_mask, bool)
    if mask.shape != times.shape or not mask.any():
        raise ValueError("train_time_mask must select at least one timepoint")

    objective = _objective_factory(curves, times, n_components, shrinkage, mask)
    value_and_grad = jax.jit(jax.value_and_grad(objective))

    def scipy_fun(x: np.ndarray) -> tuple[float, np.ndarray]:
        value, gradient = value_and_grad(jnp.asarray(x))
        return float(value), np.asarray(gradient, float)

    best = None
    for start in range(max(1, starts)):
        initial = _initial_parameters(curves, times, n_components, seed + start)
        result = minimize(
            scipy_fun,
            initial,
            method="L-BFGS-B",
            jac=True,
            options={"maxiter": maxiter, "ftol": 1e-12, "gtol": 1e-8},
        )
        if np.isfinite(result.fun) and (best is None or result.fun < best.fun):
            best = result
    if best is None:
        raise RuntimeError("all rate-mixture optimization starts failed")

    bounds = rate_bounds(times)
    rates, weights = decode_parameters(best.x, curves.shape[0], n_components, bounds)
    predicted = predict_uptake(times, rates, weights)
    return RateMixtureFit(
        n_components=n_components,
        shrinkage=float(shrinkage),
        rates=rates,
        weights=weights,
        predicted=predicted,
        parameters=np.asarray(best.x),
        objective=float(best.fun),
        rmse=float(np.sqrt(np.mean((predicted - curves) ** 2))),
        success=bool(best.success),
        message=str(best.message),
        iterations=int(best.nit),
        gradient_norm=float(np.linalg.norm(best.jac)),
    )


def prediction_jacobian_diagnostics(
    fit: RateMixtureFit,
    times: np.ndarray,
    *,
    relative_tolerance: float = 1e-8,
) -> JacobianDiagnostics:
    """Local information content of predicted curves with respect to all fit parameters."""
    times = np.asarray(times, float)
    n_peptides = fit.weights.shape[0]
    bounds = rate_bounds(times)

    def predicted_vector(parameters: jax.Array) -> jax.Array:
        rates, weights = _decode_jax(
            parameters, n_peptides, fit.n_components, bounds[0], bounds[1]
        )
        basis = 1.0 - jnp.exp(-jnp.asarray(times)[:, None] * rates[None, :])
        return (weights[:, :-1] @ basis.T).reshape(-1)

    jacobian = np.asarray(jax.jacobian(predicted_vector)(jnp.asarray(fit.parameters)), float)
    singular_values = np.linalg.svd(jacobian, compute_uv=False)
    leading = float(singular_values[0]) if len(singular_values) else 0.0
    relative = singular_values / leading if leading > 0 else np.zeros_like(singular_values)
    rank = int(np.sum(relative > relative_tolerance))
    probabilities = singular_values / singular_values.sum() if singular_values.sum() else singular_values
    positive = probabilities > 0
    effective_rank = (
        float(np.exp(-np.sum(probabilities[positive] * np.log(probabilities[positive]))))
        if np.any(positive)
        else 0.0
    )
    smallest_relative = float(relative[-1]) if len(relative) else 0.0
    condition = float(1.0 / smallest_relative) if smallest_relative > 0 else float("inf")
    return JacobianDiagnostics(
        n_observations=int(jacobian.shape[0]),
        n_parameters=int(jacobian.shape[1]),
        numerical_rank=rank,
        effective_rank=effective_rank,
        condition_number=condition,
        smallest_relative_singular_value=smallest_relative,
    )


def chronological_folds(n_timepoints: int, n_folds: int = 5) -> tuple[np.ndarray, ...]:
    indices = np.arange(n_timepoints)
    return tuple(np.asarray(block, int) for block in np.array_split(indices, n_folds))


def select_shared_rate_model(
    curves: np.ndarray,
    times: np.ndarray,
    *,
    components: Sequence[int] = (1, 2, 3),
    shrinkages: Sequence[float] = (0, 1e-4, 1e-3, 1e-2, 1e-1, 1, 10, 100),
    starts: int = 20,
    seed: int = 1729,
) -> ModelSelectionResult:
    curves = np.asarray(curves, float)
    folds = chronological_folds(curves.shape[1])
    rows: list[dict[str, float | int]] = []
    for n_components in components:
        for shrinkage in shrinkages:
            rmses = []
            for fold_index, held_out in enumerate(folds):
                mask = np.ones(curves.shape[1], bool)
                mask[held_out] = False
                fit = fit_shared_rate_mixture(
                    curves,
                    times,
                    n_components,
                    shrinkage,
                    train_time_mask=mask,
                    starts=starts,
                    seed=seed + 1000 * fold_index + 100 * n_components,
                )
                rmses.append(float(np.sqrt(np.mean((fit.predicted[:, held_out] - curves[:, held_out]) ** 2))))
            rows.append(
                {
                    "n_components": int(n_components),
                    "shrinkage": float(shrinkage),
                    "mean_validation_rmse": float(np.mean(rmses)),
                    "validation_se": float(np.std(rmses, ddof=1) / np.sqrt(len(rmses))),
                }
            )
    best = min(rows, key=lambda row: row["mean_validation_rmse"])
    threshold = float(best["mean_validation_rmse"] + best["validation_se"])
    eligible = [row for row in rows if row["mean_validation_rmse"] <= threshold]
    selected = sorted(eligible, key=lambda row: (row["n_components"], -row["shrinkage"]))[0]
    return ModelSelectionResult(
        selected_components=int(selected["n_components"]),
        selected_shrinkage=float(selected["shrinkage"]),
        rows=tuple(rows),
    )


def hessian_uncertainty(
    fit: RateMixtureFit,
    curves: np.ndarray,
    times: np.ndarray,
    *,
    condition_limit: float = 1e10,
) -> HessianUncertainty:
    curves = np.asarray(curves, float)
    times = np.asarray(times, float)
    n_peptides, n_timepoints = curves.shape
    objective = _objective_factory(
        curves, times, fit.n_components, fit.shrinkage, np.ones(n_timepoints, bool)
    )
    hessian = np.asarray(jax.hessian(objective)(jnp.asarray(fit.parameters)), float)
    hessian = (hessian + hessian.T) / 2
    epsilon = 1e-8 * float(np.trace(hessian)) / len(hessian) + 1e-12
    regularized = hessian + epsilon * np.eye(len(hessian))
    condition = float(np.linalg.cond(regularized))
    dof = max(curves.size - len(fit.parameters), 1)
    residual_variance = float(np.sum((fit.predicted - curves) ** 2) / dof)
    parameter_covariance = residual_variance / curves.size * np.linalg.pinv(regularized)

    bounds = rate_bounds(times)

    def decoded_vector(parameters: jax.Array) -> jax.Array:
        rates, weights = _decode_jax(
            parameters, n_peptides, fit.n_components, bounds[0], bounds[1]
        )
        return jnp.concatenate((rates, weights.reshape(-1)))

    jacobian = np.asarray(jax.jacobian(decoded_vector)(jnp.asarray(fit.parameters)), float)
    decoded_covariance = jacobian @ parameter_covariance @ jacobian.T
    k = fit.n_components
    weight_covariance = decoded_covariance[k:, k:]
    rate_covariance = decoded_covariance[:k, :k]

    # Conditional blocks hold the shared rates and other peptides fixed.
    conditional = np.zeros_like(weight_covariance)
    weight_jacobian = jacobian[k:]
    for peptide in range(n_peptides):
        parameter_slice = slice(k + peptide * k, k + (peptide + 1) * k)
        decoded_slice = slice(peptide * (k + 1), (peptide + 1) * (k + 1))
        block_h = regularized[parameter_slice, parameter_slice]
        block_parameter_cov = residual_variance / curves.size * np.linalg.pinv(block_h)
        block_j = weight_jacobian[decoded_slice, parameter_slice]
        conditional[decoded_slice, decoded_slice] = block_j @ block_parameter_cov @ block_j.T

    def predicted_vector(parameters: jax.Array) -> jax.Array:
        rates, weights = _decode_jax(
            parameters, n_peptides, fit.n_components, bounds[0], bounds[1]
        )
        basis = 1.0 - jnp.exp(-jnp.asarray(times)[:, None] * rates[None, :])
        return (weights[:, :-1] @ basis.T).reshape(-1)

    curve_jacobian = np.asarray(jax.jacobian(predicted_vector)(jnp.asarray(fit.parameters)), float)
    curve_covariance = curve_jacobian @ parameter_covariance @ curve_jacobian.T
    return HessianUncertainty(
        parameter_covariance=parameter_covariance,
        joint_weight_covariance=weight_covariance,
        conditional_weight_covariance=conditional,
        rate_covariance=rate_covariance,
        curve_covariance=curve_covariance,
        residual_variance=residual_variance,
        condition_number=condition,
        valid=bool(np.isfinite(condition) and condition <= condition_limit),
    )


def peptide_score_covariances(weights: np.ndarray) -> dict[str, np.ndarray]:
    """Covariance across peptide locations; this is kinetic heterogeneity, not coupling."""
    scores = np.asarray(weights, float)
    empirical = np.cov(scores, rowvar=False, ddof=0)
    if len(scores) < 2:
        ledoit = np.zeros_like(empirical)
    else:
        ledoit = LedoitWolf(assume_centered=False).fit(scores).covariance_
    return {"empirical_population": empirical, "ledoit_wolf": ledoit}


def project_curves_to_rates(
    curves: np.ndarray,
    times: np.ndarray,
    rates: np.ndarray,
    *,
    starts: int = 10,
    seed: int = 1729,
) -> tuple[np.ndarray, np.ndarray]:
    """Project curves into a fixed rate basis by simplex-constrained least squares."""
    curves = np.asarray(curves, float)
    basis = uptake_basis(times, rates)
    n_peptides, n_components = curves.shape[0], len(rates)
    fitted_weights = np.empty((n_peptides, n_components + 1))
    fitted_curves = np.empty_like(curves)
    for peptide, target in enumerate(curves):
        def objective(logits: np.ndarray) -> tuple[float, np.ndarray]:
            all_logits = jnp.concatenate((jnp.asarray(logits), jnp.zeros(1)))
            weights = jax.nn.softmax(all_logits)
            predicted = weights[:-1] @ jnp.asarray(basis).T
            loss = 0.5 * jnp.mean((predicted - jnp.asarray(target)) ** 2)
            gradient = jax.grad(
                lambda values: 0.5 * jnp.mean(
                    (jax.nn.softmax(jnp.concatenate((values, jnp.zeros(1))))[:-1]
                     @ jnp.asarray(basis).T - jnp.asarray(target)) ** 2
                )
            )(jnp.asarray(logits))
            return float(loss), np.asarray(gradient)

        best = None
        for start in range(max(1, starts)):
            rng = np.random.default_rng(seed + peptide * 100 + start)
            result = minimize(
                objective,
                rng.normal(0, 0.2, n_components),
                method="L-BFGS-B",
                jac=True,
                options={"maxiter": 500, "ftol": 1e-12},
            )
            if best is None or result.fun < best.fun:
                best = result
        logits = np.r_[best.x, 0.0]
        weights = np.exp(logits - logits.max())
        weights /= weights.sum()
        fitted_weights[peptide] = weights
        fitted_curves[peptide] = weights[:-1] @ basis.T
    return fitted_weights, fitted_curves


def mahalanobis_distance(
    left: np.ndarray, right: np.ndarray, covariance: np.ndarray
) -> float:
    difference = np.asarray(left, float) - np.asarray(right, float)
    covariance = np.asarray(covariance, float)
    epsilon = 1e-8 * float(np.trace(covariance)) / len(covariance) + 1e-12
    return float(np.sqrt(max(difference @ np.linalg.pinv(covariance + epsilon * np.eye(len(covariance))) @ difference, 0.0)))
