"""
[Script Name] splitdata_CrossVal.py

[Brief Description of Functionality]
Splits the featurised dataset into training and validation sets using various splitting strategies
(random, sequence-based, cluster-based, stratified, and spatial). It loads the experimental HDX data
and the feature topology to ensure compatibility.

Requirements:
    - Experimental Data (in `../../data/_MoPrP/_output/`):
        - `MoPrP_dfrac.dat`
        - `MoPrP_segments.txt`
    - Featurised Topology: `_featurise/topology_AF2_filtered.json` (generated by featurise script)
    - MDAnalysis Universe (for spatial splitting)

Usage:
    python jaxent/examples/2_CrossValidation/fitting/jaxENT/splitdata_CrossVal.py

Output:
    - Data split directories in `_datasplits/{split_type}/split_{idx}/`.
    - Each split contains:
        - `train_topology.json`, `train_dfrac.csv`
        - `val_topology.json`, `val_dfrac.csv`
    - Full dataset saved in `_datasplits/full_dataset_topology.json` and `full_dataset_dfrac.csv`.
"""

import os

import MDAnalysis as mda
import numpy as np
import pandas as pd

import jaxent.src.interfaces.topology as pt
from jaxent.src.custom_types.datapoint import ExpD_Datapoint
from jaxent.src.custom_types.HDX import HDX_peptide
from jaxent.src.data.loader import ExpD_Dataloader
from jaxent.src.data.splitting.split import DataSplitter


def run_data_splits(
    num_splits: int,
    output_dir: str,
    HDX_data: list[HDX_peptide],
    feature_topology: list[pt.Partial_Topology],
    split_type: str = "random",
    remove_overlap: bool = True,
    universe: mda.Universe | None = None,  # Added universe parameter
) -> None:
    """
    Run multiple data splits and save each to its own folder

    Args:
        num_splits: Number of different splits to generate
        output_dir: Base directory to save all splits
        HDX_data: list of HDX_peptide objects
        feature_topology: list of Partial_Topology objects for features
        split_type: Type of split to perform
        remove_overlap: Whether to remove overlapping residues between train and val sets
    """
    os.makedirs(output_dir, exist_ok=True)

    for split_idx in range(num_splits):
        print(f"\n=== Running split {split_idx + 1}/{num_splits} for type {split_type} ===")

        # Create split-specific folder
        split_dir: str = os.path.join(output_dir, f"split_{split_idx:03d}")
        os.makedirs(split_dir, exist_ok=True)

        # Create dataloader and splitter with different random seed for each split
        HDX_dataloader: ExpD_Dataloader = ExpD_Dataloader(data=HDX_data)
        splitter: DataSplitter = DataSplitter(
            train_size=0.5,
            dataset=HDX_dataloader,
            common_residues=set(feature_topology),
            peptide_trim=2,
            centrality=False,
            check_trim=True,
            min_split_size=4,
            random_seed=42 * split_idx,  # Different seed for each split
        )

        # Select the splitting method based on split_type
        if split_type == "random":
            train_data, val_data = splitter.random_split(remove_overlap=remove_overlap)
        elif split_type == "sequence":
            train_data, val_data = splitter.sequence_split(remove_overlap=remove_overlap)
        elif split_type == "sequence_cluster":
            train_data, val_data = splitter.sequence_cluster_split(
                remove_overlap=remove_overlap, n_clusters=7
            )
        elif split_type == "stratified":
            train_data, val_data = splitter.stratified_split(remove_overlap=remove_overlap)
        elif split_type == "spatial":
            if universe is None:
                raise ValueError("MDAnalysis Universe must be provided for spatial split.")
            train_data, val_data = splitter.spatial_split(
                universe=universe, remove_overlap=remove_overlap
            )
        else:
            raise ValueError(f"Unknown split type: {split_type}")

        print(f"Train data size: {len(train_data)}")
        print(f"Validation data size: {len(val_data)}")

        # Save training data
        # save_split_data(train_data, split_dir, "train")
        ExpD_Datapoint.save_list_to_files(
            train_data,
            json_path=os.path.join(split_dir, "train_topology.json"),
            csv_path=os.path.join(split_dir, "train_dfrac.csv"),
        )
        # Save validation data
        ExpD_Datapoint.save_list_to_files(
            val_data,
            json_path=os.path.join(split_dir, "val_topology.json"),
            csv_path=os.path.join(split_dir, "val_dfrac.csv"),
        )
        print(f"Split {split_idx + 1} saved to {split_dir}")


def main() -> None:
    HDX_dir: str = "../../data/_MoPrP/_output"
    HDX_dir = os.path.join(os.path.dirname(__file__), HDX_dir)
    if not os.path.exists(HDX_dir):
        raise FileNotFoundError(f"HDX directory does not exist: {HDX_dir}")

    dfrac_file: str = "MoPrP_dfrac.dat"
    segs_file: str = "MoPrP_segments.txt"
    output_dir: str = os.path.join(os.path.dirname(__file__), "_datasplits")
    feature_topology_file: str = "topology_AF2_filtered.json"
    features_dir: str = os.path.join(os.path.dirname(__file__), "_featurise")

    if not os.path.exists(features_dir):
        raise FileNotFoundError(f"Features directory does not exist: {features_dir}")

    num_splits: int = 3
    chain: str = "A"

    # Load feature topology
    feature_topology: list[pt.Partial_Topology] = pt.PTSerialiser.load_list_from_json(
        filepath=os.path.join(features_dir, feature_topology_file)
    )
    print(f"Feature topology loaded with {len(feature_topology)} fragments.")

    # Load dfrac and segments data
    dfrac: np.ndarray = pd.read_csv(
        os.path.join(HDX_dir, dfrac_file),
        sep='\s+',
        comment="#",
        header=None,
    ).to_numpy()

    segs: np.ndarray = pd.read_csv(
        os.path.join(HDX_dir, segs_file),
        sep='\s+',
        comment="#",
        header=None,
    ).to_numpy()

    # Create HDX topology objects
    HDX_topology: list[pt.Partial_Topology] = [
        pt.TopologyFactory.from_range(
            chain=chain,
            start=seg[0],
            end=seg[1],
            fragment_index=idx,
            peptide=True,
            peptide_trim=2,
            fragment_name="MoPrPCrossVal",
        )
        for idx, seg in enumerate(segs)
    ]
    print(f"Loaded {len(HDX_topology)} segments from {segs_file}.")

    # Create HDX data objects
    HDX_data: list[HDX_peptide] = [
        HDX_peptide(dfrac=dfrac[idx], top=HDX_topology[idx]) for idx in range(len(segs) - 2)
    ]
    print(f"Created {len(HDX_data)} HDX_peptide objects.")

    # Save the full loaded dataset
    print(f"\nSaving full dataset to {output_dir}...")
    os.makedirs(output_dir, exist_ok=True)
    ExpD_Datapoint.save_list_to_files(
        HDX_data,
        json_path=os.path.join(output_dir, "full_dataset_topology.json"),
        csv_path=os.path.join(output_dir, "full_dataset_dfrac.csv"),
    )

    # Run multiple data splits for each split type
    split_types = ["random", "sequence", "sequence_cluster", "stratified", "spatial"]
    remove_overlap = True  # Or configure as needed

    # Load MDAnalysis Universe for spatial split
    import MDAnalysis as mda

    # Define the path to the closed state topology and a representative trajectory
    # These paths are relative to the 'splitdata_ISO.py' script
    traj_base_dir = os.path.join(os.path.dirname(__file__), "../../data/")
    closed_topology_file = os.path.join(traj_base_dir, "MoPrP_max_plddt_4334.pdb")
    # Using the filtered sliced trajectory as a representative for spatial calculations
    representative_trajectory_file = os.path.join(
        traj_base_dir, "_cluster_MoPrP_filtered/clusters/all_clusters.xtc"
    )

    try:
        universe = mda.Universe(closed_topology_file)
        print(
            f"Loaded MDAnalysis Universe from {closed_topology_file} and {representative_trajectory_file}"
        )
    except Exception as e:
        print(f"Warning: Could not load MDAnalysis Universe for spatial split: {e}")
        universe = None  # Set to None if loading fails

    for split_type in split_types:
        split_output_dir = os.path.join(output_dir, split_type)
        print(f"\n--- Generating {num_splits} splits for type: {split_type} ---")
        if split_type == "spatial" and universe is None:
            print("Skipping spatial split as MDAnalysis Universe could not be loaded.")
            continue
        run_data_splits(
            num_splits=num_splits,
            output_dir=split_output_dir,
            HDX_data=HDX_data,
            feature_topology=feature_topology,
            split_type=split_type,
            remove_overlap=remove_overlap,
            universe=universe,  # Pass universe to run_data_splits
        )

    print(f"\nAll splits completed and saved to: {output_dir}")


if __name__ == "__main__":
    main()
